// Decorations are independent of wardrobe, expression and location state.
const decorationTypes={heart:'Heart',star:'Star',flame:'Flame',sparkle:'Sparkle',bolt:'Lightning',butterfly:'Butterfly'};
const decorationState={items:[],selected:null,nextId:1,history:[]};
const decorationLayer=document.createElement('div');decorationLayer.className='decoration-layer';decorationLayer.setAttribute('aria-label','Scene decorations');stage.append(decorationLayer);
const wardrobePanel=document.querySelector('.wardrobe');
const wardrobeContent=document.createElement('div');wardrobeContent.className='wardrobe-content';
while(wardrobePanel.firstChild)wardrobeContent.append(wardrobePanel.firstChild);
const editTabs=document.createElement('div');editTabs.className='editor-tabs';editTabs.setAttribute('role','tablist');editTabs.setAttribute('aria-label','Scene editor');
editTabs.innerHTML='<button id="wardrobe-tab" role="tab" aria-selected="true" aria-controls="wardrobe-content">Wardrobe</button><button id="decorate-tab" role="tab" aria-selected="false" aria-controls="decoration-panel" tabindex="-1">Decorate</button>';
wardrobeContent.id='wardrobe-content';wardrobeContent.setAttribute('role','tabpanel');wardrobeContent.setAttribute('aria-labelledby','wardrobe-tab');
const decorationPanel=document.createElement('div');decorationPanel.id='decoration-panel';decorationPanel.hidden=true;decorationPanel.setAttribute('role','tabpanel');decorationPanel.setAttribute('aria-labelledby','decorate-tab');
decorationPanel.innerHTML='<div class="section-label"><span>03</span> MAKE IT YOURS <b id="decoration-count">0 / 30</b></div><p class="decoration-hint">Add a sticker, then drag it anywhere in the scene.</p><div class="sticker-palette"></div><div class="sticker-inspector"><div class="inspector-title"><strong id="sticker-selection">Select a sticker to edit</strong><button class="small-button" id="undo-sticker" disabled>Undo</button></div><label for="sticker-size">Size <output id="size-value">56 px</output></label><input id="sticker-size" type="range" min="28" max="112" step="1" value="56" disabled><label for="sticker-rotation">Rotation <output id="rotation-value">0°</output></label><input id="sticker-rotation" type="range" min="-180" max="180" step="5" value="0" disabled><div class="sticker-actions"><button class="button" id="duplicate-sticker" disabled>Duplicate</button><button class="button" id="remove-sticker" disabled>Remove</button></div><p class="keyboard-tip">Arrow keys move a selected sticker. Delete removes it.</p></div><button class="button clear-stickers" id="clear-stickers" disabled>Clear decorations</button>';
wardrobePanel.append(editTabs,wardrobeContent,decorationPanel);
function openEditorTab(name){const decorate=name==='decorate';wardrobeContent.hidden=decorate;decorationPanel.hidden=!decorate;editTabs.querySelectorAll('button').forEach((b,i)=>{const yes=decorate?i===1:i===0;b.setAttribute('aria-selected',String(yes));b.tabIndex=yes?0:-1})}
editTabs.querySelectorAll('button').forEach((b,i)=>{b.onclick=()=>openEditorTab(i?'decorate':'wardrobe');b.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?1:1-i;openEditorTab(n?'decorate':'wardrobe');editTabs.children[n].focus()}}});
function decorationSnapshot(){return{items:decorationState.items.map(i=>({...i})),selected:decorationState.selected}}
function rememberDecorations(){decorationState.history.push(decorationSnapshot());if(decorationState.history.length>40)decorationState.history.shift()}
function selectedDecoration(){return decorationState.items.find(i=>i.id===decorationState.selected)}
function clampDecoration(item){const rect=stage.getBoundingClientRect(),r=item.size*.71;item.x=Math.max(r/rect.width,Math.min(1-r/rect.width,item.x));item.y=Math.max(r/rect.height,Math.min(1-r/rect.height,item.y));return item}
function positionDecoration(el,item){clampDecoration(item);el.style.left=item.x*100+'%';el.style.top=item.y*100+'%';el.style.width=item.size+'px';el.style.height=item.size+'px';el.style.transform='translate(-50%,-50%) rotate('+item.rotation+'deg)';el.dataset.x=item.x.toFixed(4);el.dataset.y=item.y.toFixed(4)}
function updateDecorationControls(){const item=selectedDecoration();document.querySelector('#decoration-count').textContent=decorationState.items.length+' / 30';document.querySelector('#sticker-selection').textContent=item?decorationTypes[item.type]+' selected':'Select a sticker to edit';for(const id of ['sticker-size','sticker-rotation','duplicate-sticker','remove-sticker'])document.getElementById(id).disabled=!item;document.querySelector('#clear-stickers').disabled=!decorationState.items.length;document.querySelector('#undo-sticker').disabled=!decorationState.history.length;if(item){document.querySelector('#sticker-size').value=item.size;document.querySelector('#sticker-rotation').value=item.rotation;document.querySelector('#size-value').value=item.size+' px';document.querySelector('#rotation-value').value=item.rotation+'°'}decorationLayer.querySelectorAll('.placed-sticker').forEach(el=>el.setAttribute('aria-pressed',String(Number(el.dataset.id)===decorationState.selected)))}
function renderDecorations(){decorationLayer.replaceChildren();for(const item of decorationState.items){const el=document.createElement('button');el.type='button';el.className='placed-sticker';el.dataset.id=item.id;el.setAttribute('aria-label',decorationTypes[item.type]+' decoration '+item.id);el.innerHTML='<img src="assets/sticker-'+item.type+'.png" alt="" draggable="false">';positionDecoration(el,item);el.onclick=()=>{decorationState.selected=item.id;updateDecorationControls()};el.onkeydown=e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Delete','Backspace'].includes(e.key)){e.preventDefault();decorationState.selected=item.id;if(e.key==='Delete'||e.key==='Backspace'){removeDecoration(item.id);document.querySelector('#decorate-tab').focus();return}rememberDecorations();const step=e.shiftKey?.05:.01;item.x+=e.key==='ArrowLeft'?-step:e.key==='ArrowRight'?step:0;item.y+=e.key==='ArrowUp'?-step:e.key==='ArrowDown'?step:0;positionDecoration(el,item);updateDecorationControls()}};el.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();el.focus({preventScroll:true});decorationState.selected=item.id;rememberDecorations();updateDecorationControls();const rect=stage.getBoundingClientRect(),offsetX=e.clientX-rect.left-item.x*rect.width,offsetY=e.clientY-rect.top-item.y*rect.height;el.setPointerCapture(e.pointerId);el.classList.add('dragging');const move=ev=>{if(ev.pointerId!==e.pointerId)return;const bounds=stage.getBoundingClientRect();item.x=(ev.clientX-bounds.left-offsetX)/bounds.width;item.y=(ev.clientY-bounds.top-offsetY)/bounds.height;positionDecoration(el,item)};const end=ev=>{if(ev.pointerId!==e.pointerId)return;el.classList.remove('dragging');el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',end);el.removeEventListener('pointercancel',end);if(el.hasPointerCapture(e.pointerId))el.releasePointerCapture(e.pointerId);document.querySelector('#status').textContent=decorationTypes[item.type]+' moved.'};el.addEventListener('pointermove',move);el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end)};decorationLayer.append(el)}updateDecorationControls()}
function addDecoration(type,options={}){if(!Object.hasOwn(decorationTypes,type))throw new Error('Choose a listed sticker.');if(decorationState.items.length>=30)throw new Error('Up to 30 decorations per scene. Remove one to add another.');rememberDecorations();const index=decorationState.items.length,item={id:decorationState.nextId++,type,x:options.x??(index%2?.78:.22),y:options.y??(.26+(Math.floor(index/2)%4)*.15),size:options.size??56,rotation:options.rotation??0};clampDecoration(item);decorationState.items.push(item);decorationState.selected=item.id;renderDecorations();document.querySelector('#status').textContent=decorationTypes[type]+' added. Drag it to place.';return{...item}}
function removeDecoration(id){const index=decorationState.items.findIndex(i=>i.id===id);if(index<0)throw new Error('Sticker not found.');rememberDecorations();decorationState.items.splice(index,1);if(decorationState.selected===id)decorationState.selected=null;renderDecorations();document.querySelector('#status').textContent='Decoration removed.'}
for(const [type,name] of Object.entries(decorationTypes)){const b=document.createElement('button');b.className='sticker-choice';b.setAttribute('aria-label','Add '+name+' sticker');b.innerHTML='<img src="assets/sticker-'+type+'.png" alt="" draggable="false"><span>'+name+'</span>';b.onclick=()=>{try{addDecoration(type);if(innerWidth<=620)stage.scrollIntoView({behavior:reducedMotion.matches?'instant':'smooth',block:'center'})}catch(e){document.querySelector('#status').textContent=e.message}};decorationPanel.querySelector('.sticker-palette').append(b)}
for(const [id,key,output,unit] of [['sticker-size','size','size-value',' px'],['sticker-rotation','rotation','rotation-value','°']]){const range=document.getElementById(id);range.addEventListener('pointerdown',()=>{if(selectedDecoration())rememberDecorations()});range.addEventListener('keydown',e=>{if(e.key.startsWith('Arrow')||['Home','End','PageUp','PageDown'].includes(e.key)){if(selectedDecoration())rememberDecorations()}});range.oninput=()=>{const item=selectedDecoration();if(!item)return;item[key]=Number(range.value);positionDecoration(decorationLayer.querySelector('[data-id="'+item.id+'"]'),item);document.getElementById(output).value=item[key]+unit;updateDecorationControls()}}
document.querySelector('#duplicate-sticker').onclick=()=>{const item=selectedDecoration();if(item)try{addDecoration(item.type,{...item,x:item.x+.08,y:item.y+.06})}catch(e){document.querySelector('#status').textContent=e.message}};
document.querySelector('#remove-sticker').onclick=()=>{const item=selectedDecoration();if(item)removeDecoration(item.id)};
document.querySelector('#clear-stickers').onclick=()=>{rememberDecorations();decorationState.items=[];decorationState.selected=null;renderDecorations();document.querySelector('#status').textContent='Decorations cleared. Undo is available.'};
document.querySelector('#undo-sticker').onclick=()=>{const snapshot=decorationState.history.pop();if(snapshot){decorationState.items=snapshot.items;decorationState.selected=snapshot.selected;renderDecorations();document.querySelector('#status').textContent='Last decoration edit undone.'}};
new ResizeObserver(()=>{decorationState.items.forEach(i=>{const el=decorationLayer.querySelector('[data-id="'+i.id+'"]');if(el)positionDecoration(el,i)})}).observe(stage);
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'edit_decoration',description:'Add, move, resize, rotate or remove a pixel sticker in the scene; preserves outfit and backdrop.',inputSchema:{type:'object',properties:{action:{type:'string',enum:['add','update','remove','list']},type:{type:'string',enum:Object.keys(decorationTypes)},id:{type:'integer',minimum:1},x:{type:'number',minimum:0,maximum:1},y:{type:'number',minimum:0,maximum:1},size:{type:'integer',minimum:28,maximum:112},rotation:{type:'integer',minimum:-180,maximum:180}},required:['action'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).some(k=>!['action','type','id','x','y','size','rotation'].includes(k)))throw new Error('Invalid decoration input.');if(!['add','update','remove','list'].includes(input.action))throw new Error('Choose a listed action.');for(const [key,min,max] of [['x',0,1],['y',0,1],['size',28,112],['rotation',-180,180]])if(key in input&&(!Number.isFinite(input[key])||input[key]<min||input[key]>max||(['size','rotation'].includes(key)&&!Number.isInteger(input[key]))))throw new Error('Invalid '+key);if(input.action==='list')return decorationSnapshot();if(input.action==='add'){const result=addDecoration(input.type,input);openEditorTab('decorate');return result}const item=decorationState.items.find(i=>i.id===input.id);if(!item)throw new Error('Sticker not found.');if(input.action==='remove'){removeDecoration(item.id);return{removed:input.id}}rememberDecorations();for(const k of ['x','y','size','rotation'])if(k in input)item[k]=input[k];decorationState.selected=item.id;renderDecorations();openEditorTab('decorate');return{...item}}})).catch(()=>{})}catch{}}
